//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rensoft.TechCentre.WebSite {
    
    
    public partial class CustomContent {
        
        /// <summary>
        /// PayPalControlTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rensoft.TechCentre.WebSite.PayPal.PayPalControl PayPalControlTop;
        
        /// <summary>
        /// CustomContentLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal CustomContentLiteral;
        
        /// <summary>
        /// PayPalControlBottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rensoft.TechCentre.WebSite.PayPal.PayPalControl PayPalControlBottom;
    }
}
