//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rensoft.TechCentre.WebSite.Charity {
    
    
    public partial class Default {
        
        /// <summary>
        /// PayPalControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rensoft.TechCentre.WebSite.PayPal.PayPalControl PayPalControl1;
        
        /// <summary>
        /// ContentLoader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rensoft.TechCentre.WebSite.ContentLoader ContentLoader1;
        
        /// <summary>
        /// PayPalControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rensoft.TechCentre.WebSite.PayPal.PayPalControl PayPalControl2;
    }
}
